import { Geist, Geist_Mono } from "next/font/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Web3AuthProvider } from "@web3auth/modal/react";
import { WagmiProvider } from "@web3auth/modal/react/wagmi";
import { WEB3AUTH_NETWORK } from "@web3auth/modal";
import Head from "next/head";
import "../styles/globals.css";

// Initialize fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Initialize query client
const queryClient = new QueryClient();

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Web3AuthProvider
        config={{
          web3AuthOptions: {
            clientId:
              "BMpTlXu4ij7uSZydEOU0cNZRQEN8_epocm-oNpVzFipkf3yzJLaraNIxcdqeJDHVYTIZ-uWufVeJ95s32b0eszQ",
            web3AuthNetwork: WEB3AUTH_NETWORK.SAPPHIRE_MAINNET,
          },
        }}
      >
        <QueryClientProvider client={queryClient}>
          <WagmiProvider>
            <div
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Component {...pageProps} />
            </div>
          </WagmiProvider>
        </QueryClientProvider>
      </Web3AuthProvider>
    </>
  );
}

export default MyApp;
